# Generated by Django 5.2.4 on 2025-08-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_add_doctor_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='forwarded_to_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='chatmessage',
            table='chatbot_chatmessage',
        ),
        migrations.AlterModelTable(
            name='conversation',
            table='chatbot_conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
