# Generated by Django 5.2.4 on 2025-08-28 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatmessage_forwarded_to_doctor_and_more'),
        ('chatbot', '0004_add_forwarded_to_doctor'),
    ]

    operations = [
    ]
