# Generated by Django 5.2.4 on 2025-08-28 13:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_rename_chatmessage_doctorchatmessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorChatMessage',
            new_name='ChatMessage',
        ),
        migrations.RenameModel(
            old_name='DoctorConversation',
            new_name='Conversation',
        ),
        migrations.AlterModelTable(
            name='chatmessage',
            table='doctor_chatmessage',
        ),
        migrations.AlterModelTable(
            name='conversation',
            table='doctor_conversation',
        ),
    ]
