# Generated by Django 5.2.4 on 2025-08-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_create_conversation_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_forwarded',
            field=models.BooleanField(default=False),
        ),
    ]
