# Generated by Django 4.2.10 on 2025-07-15 12:52

from django.db import migrations, models
import django.utils.timezone

# ...
field=models.DateTimeField(default=django.utils.timezone.now),



class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0044_appointment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_review',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
