# Generated by Django 4.2.10 on 2025-07-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0045_doctor_review_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
