# Generated by Django 4.1.13 on 2025-07-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0046_alter_doctor_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_information',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
